context:
  name: libmodplug
  version: "0.8.9.0"

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://downloads.sourceforge.net/project/modplug-xmms/${{ name }}/${{ version }}/${{ name }}-${{ version }}.tar.gz
  sha256: 457ca5a6c179656d66c01505c0d95fafaead4329b9dbaa0f997d00a3508ad9de
  patches:
    - 001-fix-non-const-stack-alloc.patch
    - if: win
      then: 002-fix-dll-export-mismatch.patch

build:
  number: 0

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ stdlib('c') }}
    - cmake
    - ninja
  run_exports:
    - ${{ pin_subpackage(name, upper_bound="x.x") }}

tests:
  - package_contents:
      lib:
        - modplug
      include:
        - libmodplug/it_defs.h
        - libmodplug/modplug.h
        - libmodplug/sndfile.h
        - libmodplug/stdafx.h

about:
  homepage: http://modplug-xmms.sf.net/
  summary: libmodplug is an open-source library for playing MOD audio files
  description: |
    libmodplug is an open-source library for playing MOD audio files (and related tracker formats like S3M, IT, XM). It’s often used in games and multimedia apps to add music playback without needing external dependencies.
  license: BSD-3-Clause OR LicenseRef-Public-Domain
  license_file: COPYING
  repository: https://sourceforge.net/projects/modplug-xmms/

extra:
  recipe-maintainers:
    - baszalmstra
